name: Build Windows EXE

on:
  push:              # roda a cada push na branch principal
    branches: [ main ]
  workflow_dispatch: # ou manualmente pelo botão "Run workflow"

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # 1) Clona seu repositório
      - uses: actions/checkout@v4

      # 2) Instala Python 3.12 no runner
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3) Instala dependências e PyInstaller
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # 4) Gera o executável
      - run: |
          pyinstaller desktop_app.py ^
            --noconfirm ^
            --onefile ^
            --windowed ^
            --add-data "app;app" ^
            --icon "app/static/img/brmed-new-logo.ico"

      # 5) Publica o EXE como artefato
      - uses: actions/upload-artifact@v4
        with:
          name: desktop_app.exe
          path: dist/desktop_app.exe
