name: Build Windows EXE

on:
  push:
    branches: [main]      # execute a cada push na branch main
  workflow_dispatch:      # também manualmente pelo botão "Run workflow"

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller python-dotenv

      - name: Generate .env and config.ini
        shell: bash          
        run: |
          echo "${{ secrets.ENV_CONTENTS }}" > .env
          echo "${{ secrets.CONFIG_INI }}"   > config.ini

      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          pyinstaller desktop_app.py ^
            --noconfirm ^
            --onefile ^
            --windowed ^
            --add-data "app;app" ^
            --add-data ".env;." ^
            --add-data "config.ini;." ^

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: desktop_app.exe         
          path: dist/desktop_app.exe     
